//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8937
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REHBER.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REHBER.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _20121011142540_2022f426_me {
            get {
                object obj = ResourceManager.GetObject("20121011142540-2022f426-me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _58c2520ac03c0e22948311cf {
            get {
                object obj = ResourceManager.GetObject("58c2520ac03c0e22948311cf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _95746129_address_phone_book_icon_notebook_icon_flat_design_style {
            get {
                object obj = ResourceManager.GetObject("95746129-address-phone-book-icon-notebook-icon-flat-design-style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _95746183_address_phone_book_icon_notebook_icon_flat_design_style {
            get {
                object obj = ResourceManager.GetObject("95746183-address-phone-book-icon-notebook-icon-flat-design-style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add1 {
            get {
                object obj = ResourceManager.GetObject("add1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contacts_icon_47413_222x231 {
            get {
                object obj = ResourceManager.GetObject("contacts-icon-47413_222x231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contacts_icon_47413_222x2311 {
            get {
                object obj = ResourceManager.GetObject("contacts-icon-47413_222x2311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete1 {
            get {
                object obj = ResourceManager.GetObject("delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositphotos_129229614_stock_illustration_phonebook_icon_vector_design_telephone {
            get {
                object obj = ResourceManager.GetObject("depositphotos_129229614-stock-illustration-phonebook-icon-vector-design-telephone" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositphotos_54680469_stock_illustration_flat_icon_of_contacts_book {
            get {
                object obj = ResourceManager.GetObject("depositphotos_54680469-stock-illustration-flat-icon-of-contacts-book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file1 {
            get {
                object obj = ResourceManager.GetObject("file1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file2 {
            get {
                object obj = ResourceManager.GetObject("file2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images3 {
            get {
                object obj = ResourceManager.GetObject("images3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imagesCAD7UKBI {
            get {
                object obj = ResourceManager.GetObject("imagesCAD7UKBI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loupe {
            get {
                object obj = ResourceManager.GetObject("loupe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap my_contacts_backup_ios_rehber_ve_mesaj_yedekleme_uygulamasi {
            get {
                object obj = ResourceManager.GetObject("my-contacts-backup-ios-rehber-ve-mesaj-yedekleme-uygulamasi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap numbered_list {
            get {
                object obj = ResourceManager.GetObject("numbered-list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap numbered_lists64 {
            get {
                object obj = ResourceManager.GetObject("numbered-lists64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap numbered_lists641 {
            get {
                object obj = ResourceManager.GetObject("numbered-lists641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_book {
            get {
                object obj = ResourceManager.GetObject("phone-book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smartphone {
            get {
                object obj = ResourceManager.GetObject("smartphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wiping_swipe_for_floors {
            get {
                object obj = ResourceManager.GetObject("wiping-swipe-for-floors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wiping_swipe_for_floors1 {
            get {
                object obj = ResourceManager.GetObject("wiping-swipe-for-floors1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
